package org.example.fleet.delivery.repository;

import org.h2.jdbcx.JdbcDataSource;

import javax.sql.DataSource;
import java.sql.SQLException;

final class RepositoryTestSupport {
    private RepositoryTestSupport() {
    }

    static DataSource createDatabase(String name) throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:" + name + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        try (var connection = dataSource.getConnection(); var statement = connection.createStatement()) {
            statement.execute("CREATE TABLE repartidores (device_id VARCHAR(64) PRIMARY KEY, "
                + "nombre VARCHAR(120) NOT NULL, msisdn VARCHAR(20))");
            statement.execute("CREATE TABLE pedidos (id VARCHAR(50) PRIMARY KEY, "
                + "cliente_nombre VARCHAR(120) NOT NULL, cliente_msisdn VARCHAR(20) NOT NULL, "
                + "cliente_fcm_id VARCHAR(255), direccion_texto VARCHAR(255), "
                + "lat_destino DOUBLE PRECISION NOT NULL, lon_destino DOUBLE PRECISION NOT NULL, "
                + "radio_llegada_m INTEGER NOT NULL, repartidor_device_id VARCHAR(64) NOT NULL, "
                + "estado VARCHAR(20) NOT NULL, fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL, "
                + "fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL, "
                + "FOREIGN KEY (repartidor_device_id) REFERENCES repartidores(device_id))");
            statement.execute("CREATE TABLE pedido_ultima_posicion (pedido_id VARCHAR(50) PRIMARY KEY, "
                + "device_id VARCHAR(64) NOT NULL, message_id VARCHAR(64), lat DOUBLE PRECISION NOT NULL, "
                + "lon DOUBLE PRECISION NOT NULL, velocidad_kmh DOUBLE PRECISION, "
                + "distancia_destino_m DOUBLE PRECISION, timestamp TIMESTAMP WITH TIME ZONE NOT NULL, "
                + "FOREIGN KEY (pedido_id) REFERENCES pedidos(id))");
            statement.execute("CREATE TABLE pedido_eventos (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "pedido_id VARCHAR(50) NOT NULL, hito VARCHAR(30) NOT NULL, detalle JSON, "
                + "notificado BOOLEAN NOT NULL DEFAULT FALSE, timestamp TIMESTAMP WITH TIME ZONE NOT NULL, "
                + "UNIQUE (pedido_id, hito), FOREIGN KEY (pedido_id) REFERENCES pedidos(id))");
            statement.execute("INSERT INTO repartidores VALUES ('repartidor-01', 'Demo', '+595981000001')");
        }
        return dataSource;
    }
}
